# Site
url: "https://wpoverman.github.io"
baseurl: ""   # IMPORTANT: empty for a user/organization site at root

# Jekyll defaults
source:      .
destination: ./_site
includes:    ./_includes

collections:
  projects:
    output: true
